// Exports the SF Symbols used by src/components/Icon.tsx as black-on-transparent PNGs.
// Run from the repository root: npm run symbols
// The output is generated on the build machine and is not tracked in git.
// Each symbol is written at 3x as <name>.png, and symbols.css declares one mask class per symbol.
#if !os(macOS)
#error("Exporting SF Symbols requires macOS.")
#endif
import AppKit

let symbols: [(name: String, symbol: String)] = [
    ("refresh", "arrow.clockwise"),
    ("pause", "pause.fill"),
    ("play", "play.fill"),
    ("gear", "gearshape"),
    ("search", "magnifyingglass"),
    ("disclosure", "chevron.right"),
    ("person", "person.crop.circle"),
    ("folder", "folder"),
    ("branch", "arrow.triangle.branch"),
    ("filter", "line.3.horizontal.decrease.circle"),
    ("bell", "bell"),
    ("plus", "plus"),
    ("minus", "minus"),
    ("check", "checkmark"),
    ("warning", "exclamationmark.triangle.fill"),
    ("external", "arrow.up.forward.square"),
    ("xmark", "xmark"),
]

let pointSize: CGFloat = 16
let canvas: CGFloat = 20
let outputDir = "src/assets/symbols"

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("\(message)\n".utf8))
    exit(1)
}

// Skip the export when every output exists and is newer than this script.
func modified(_ path: String) -> Date? {
    let attributes = try? FileManager.default.attributesOfItem(atPath: path)
    return attributes?[.modificationDate] as? Date
}

if let scriptDate = modified(CommandLine.arguments[0]) {
    let outputs = symbols.map { "\(outputDir)/\($0.name).png" } + ["\(outputDir)/symbols.css"]
    let upToDate = outputs.allSatisfy { (modified($0) ?? .distantPast) > scriptDate }
    if upToDate {
        print("symbols up to date")
        exit(0)
    }
}

try FileManager.default.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

func render(_ image: NSImage, scale: Int) -> Data? {
    let pixels = Int(canvas) * scale
    guard let rep = NSBitmapImageRep(
        bitmapDataPlanes: nil, pixelsWide: pixels, pixelsHigh: pixels, bitsPerSample: 8,
        samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB,
        bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
    rep.size = NSSize(width: canvas, height: canvas)

    guard let context = NSGraphicsContext(bitmapImageRep: rep) else { return nil }
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = context

    // Scale the symbol to fit the canvas, centered, drawn in black.
    let tinted = image.copy() as! NSImage
    tinted.lockFocus()
    NSColor.black.set()
    NSRect(origin: .zero, size: tinted.size).fill(using: .sourceAtop)
    tinted.unlockFocus()

    let fit = min((canvas - 2) / tinted.size.width, (canvas - 2) / tinted.size.height, 1)
    let width = tinted.size.width * fit
    let height = tinted.size.height * fit
    tinted.draw(
        in: NSRect(x: (canvas - width) / 2, y: (canvas - height) / 2, width: width, height: height),
        from: .zero, operation: .sourceOver, fraction: 1)

    NSGraphicsContext.restoreGraphicsState()
    return rep.representation(using: .png, properties: [:])
}

var css = "/* Generated by scripts/export-symbols.swift. Do not edit. */\n"

for entry in symbols {
    let config = NSImage.SymbolConfiguration(pointSize: pointSize, weight: .regular)
    guard let base = NSImage(systemSymbolName: entry.symbol, accessibilityDescription: nil),
          let image = base.withSymbolConfiguration(config) else {
        FileHandle.standardError.write(Data("missing symbol \(entry.symbol)\n".utf8))
        exit(1)
    }
    guard let data = render(image, scale: 3) else {
        FileHandle.standardError.write(Data("render failed for \(entry.symbol)\n".utf8))
        exit(1)
    }
    try data.write(to: URL(fileURLWithPath: "\(outputDir)/\(entry.name).png"))
    css += ".symbol--\(entry.name) {\n  -webkit-mask-image: url(\"./\(entry.name).png\");\n  mask-image: url(\"./\(entry.name).png\");\n}\n"
    print("\(entry.name) <- \(entry.symbol)")
}

try css.write(toFile: "\(outputDir)/symbols.css", atomically: true, encoding: .utf8)
