// Exports the icons that src/components/Icon.tsx draws as CSS masks into src/assets/symbols.
// Run from the repository root: npm run symbols
//
// macOS builds use SF Symbols, exported by scripts/export-symbols.swift. The SF Symbols licence
// covers Apple platforms only, so Linux and Windows builds use Lucide (ISC). Set
// VIGIA_SYMBOLS=lucide to export the Lucide set on macOS and check those builds.
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/assets/symbols");
const LUCIDE_ICONS = join(ROOT, "node_modules/lucide-static/icons");
/** Names the icon set in the output, so switching sets starts from an empty directory. */
const MARKER = join(OUT, ".source");

/** The Lucide icon for each symbol name in Icon.tsx. */
const LUCIDE = {
  refresh: "rotate-cw",
  pause: "pause",
  play: "play",
  gear: "settings",
  search: "search",
  disclosure: "chevron-right",
  person: "circle-user",
  folder: "folder",
  branch: "git-branch",
  filter: "list-filter",
  bell: "bell",
  plus: "plus",
  minus: "minus",
  check: "check",
  warning: "triangle-alert",
  external: "square-arrow-out-up-right",
  xmark: "x",
};

const source = process.platform === "darwin" && process.env.VIGIA_SYMBOLS !== "lucide" ? "sf" : "lucide";

// Output without a marker comes from export-symbols.swift run on its own.
const exported = existsSync(join(OUT, "symbols.css")) ? "sf" : null;
const previous = existsSync(MARKER) ? readFileSync(MARKER, "utf8").trim() : exported;
if (previous !== null && previous !== source) {
  rmSync(OUT, { recursive: true, force: true });
}
mkdirSync(OUT, { recursive: true });

if (source === "sf") {
  execFileSync("swift", ["scripts/export-symbols.swift"], { cwd: ROOT, stdio: "inherit" });
} else {
  let css = "/* Generated by scripts/symbols.mjs. Do not edit. */\n";
  for (const [name, icon] of Object.entries(LUCIDE)) {
    copyFileSync(join(LUCIDE_ICONS, `${icon}.svg`), join(OUT, `${name}.svg`));
    css += `.symbol--${name} {\n  -webkit-mask-image: url("./${name}.svg");\n  mask-image: url("./${name}.svg");\n}\n`;
  }
  writeFileSync(join(OUT, "symbols.css"), css);
  console.log(`exported ${Object.keys(LUCIDE).length} Lucide icons`);
}

writeFileSync(MARKER, `${source}\n`);
